import { PrismaPg } from '@prisma/adapter-pg';
// Generated by `prisma generate` into backend/generated/prisma (see prisma/schema.prisma's
// generator block) - this path only exists after that command has been run.
import { PrismaClient } from '../../generated/prisma/client';
import { env } from '../config/env';

// Reuse a single PrismaClient (and its underlying pg Pool) across dev
// hot-reloads so we never exhaust the database's connection limit by
// creating a new pool on every file change.
declare global {
  var __prisma__: PrismaClient | undefined;
}

function createPrismaClient(): PrismaClient {
  const adapter = new PrismaPg({ connectionString: env.DATABASE_URL });
  return new PrismaClient({
    adapter,
    log: env.NODE_ENV === 'development' ? ['warn', 'error'] : ['error'],
  });
}

export const prisma = global.__prisma__ ?? createPrismaClient();

if (env.NODE_ENV !== 'production') {
  global.__prisma__ = prisma;
}
